# Hypixel migrator

Hypixel-api: ""
online-mode: true

Prefix: "&c[&aYourServerName&c]"

Migrate-item:
  # SKULL_ITEM :- in 1.8.8
  # PLAYER_HEAD :- in 1.19
  Item-icon: PLAYER_HEAD
  # If not using player head keep this false
  player-head: true
  player-head-skin: "hypixel"

  Item-name: "&cHypixel layout"
  Lore: ["", "&7Click here to", "&7Migrate your layout", "&7From hypixel"]

Messages:
  migration-success: "&a&lSuccess! &r&awe have migrated your layout ;)"
  not-premium-player: "&cYou dont have official minecraft account!"
  migration-started: "&aTrying to migrate your layout"
  migration-failed: "&c&lFAILED &r&c Sorry migration failed"
  migration-failed-no-perms: "&c&lFAILED &r&c Sorry you don't have permission to do that!"

