# Hypixel migrator

Hypixel-api: ""
online-mode: true

Prefix: "&c[&aYourServerName&c]"
# The category item which you use (default: nether_star)
Quick-shop-item: NETHER_STAR

Migrate-item:
  # SKULL_ITEM :- in 1.8.8
  # PLAYER_HEAD :- in 1.19
  Item-icon: REDSTONE_BLOCK
  # If not using player head keep this false
  player-head: false
  player-head-skin: "hypixel"

  Item-name: "&cHypixel layout"
  Lore: ["", "&7Click here to", "&7Migrate your layout", "&7From hypixel"]

Messages:
  migration-success: "&a&lSuccess! &r&awe have migrated your layout ;)"
  not-premium-player: "&cYou dont have official minecraft account!"
  migration-started: "&aTrying to migrate your layout"
  migration-failed: "&c&lFAILED &r&c Sorry migration failed"

