name: HypixelMigratorAddon
version: '${project.version}'
main: me.harsh.hypixelmigratoraddon.HypixelMigratorAddon
commands:
  migrate:
    aliases:
      - migrate
      - mig
    description: migrate command
    usage: /migrate